{
 "title": "Tesla",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "vin", "label": "vin", "query": "tesla_vehicle_name" },
   { "name": "tesla_name", "query": "tesla_vehicle_name" },
   { "name": "software_version", "query": "tesla_vehicle_software_version" },
   { "name": "tesla_state", "query": "tesla_vehicle_state" }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "content": "<center><font size=\"66\" color=\"blue\">${tesla_name}</font></center>\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ChargeState",
     "query": "SELECT last(\"battery_range\") FROM \"AllData\"",
     "select": [
      [
       { "params": [ "battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "软件版本号",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 0 },
   "repeat": "software_version",
   "content": "\n<center><font size=\"48\" color=\"green\">${software_version}</font></center>\n\n\n",
   "targets": [
    {
     "alias": "kWhs",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ConnectedOdometer" ], "type": "tag" }
     ],
     "measurement": "AllData",
     "query": "SELECT kWhs FROM (SELECT max(\"charge_energy_added\") AS kWhs FROM \"AllData\" WHERE (\"Connected\" = 'true') AND $timeFilter GROUP BY \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Connected", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "充电amps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "expr": "tesla_vehicle_charge_amps{vin=\"$vin\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "available",
     "measurement": "ChargeState",
     "query": "SELECT mean(\"battery_level\") FROM \"AllData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "充电volt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "tesla_vehicle_charge_volts{vin=\"$vin\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ChargeState",
     "query": "SELECT last(\"battery_level\") FROM \"AllData\"",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "充电rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "tesla_vehicle_charge_volts{vin=\"$vin\"} * tesla_vehicle_charge_amps{vin=\"$vin\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rate",
     "measurement": "ChargeState",
     "query": "SELECT last(\"battery_level\") FROM \"AllData\"",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "状态",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "content": "<center><font size=\"66\" color=\"green\">${tesla_state}</font></center>",
   "targets": [
    {
     "expr": "tesla_vehicle_state{vin=\"$vin\"}",
     "groupBy": [
      { "params": [ "Connected" ], "type": "tag" }
     ],
     "measurement": "AllData",
     "query": "SELECT sum(EA) FROM (SELECT max(\"charge_energy_added\") AS EA FROM \"AllData\" WHERE (\"Connected\" = 'true') AND $timeFilter GROUP BY \"Connected\", \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Connected", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "充电 预估/理想 里程",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "lengthkm" }
   ],
   "targets": [
    {
     "alias": "Climate Drain",
     "expr": "tesla_vehicle_battery_estimated_miles{vin=\"$vin\"} * 1.61",
     "groupBy": [
      { "params": [ "6h" ], "type": "time" }
     ],
     "legendFormat": "预估",
     "measurement": "AllData",
     "select": [
      [
       { "params": [ "lostenergy_climate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "expr": "tesla_vehicle_battery_ideal_miles{vin=\"$vin\"}  * 1.61",
     "legendFormat": "理想"
    }
   ]
  },
  {
   "title": "Amps / Volts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "tesla_vehicle_charge_amps{vin=\"$vin\"}",
     "legendFormat": "Amps",
     "measurement": "AllData",
     "query": "SELECT SUM(EA) / (MAX(odometer) - MIN(odometer))*1000 AS WhPM FROM (SELECT max(\"charge_energy_added\") AS EA, max(\"odometer\") AS odometer FROM \"AllData\" WHERE (\"Connected\" = 'true') AND $timeFilter GROUP BY \"Connected\", \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "odometer" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "expr": "tesla_vehicle_charge_volts{vin=\"$vin\"}",
     "legendFormat": "Volts"
    }
   ]
  },
  {
   "title": "Charge Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "tesla_vehicle_charge_volts{vin=\"$vin\"} * tesla_vehicle_charge_amps{vin=\"$vin\"} / 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ChargeState",
     "query": "SELECT last(\"time_to_full_charge\") FROM \"AllData\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "time_to_full_charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "总里程",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "lengthkm",
   "valueName": "current",
   "targets": [
    {
     "expr": "tesla_vehicle_odometer_miles_total{vin=\"$vin\"} * 1.61",
     "groupBy": [
      { "params": [ "Connected" ], "type": "tag" }
     ],
     "measurement": "AllData",
     "query": "SELECT sum(EA) FROM (SELECT max(\"charge_energy_added\") AS EA FROM \"AllData\" WHERE (\"Connected\" = 'true') AND $timeFilter GROUP BY \"Connected\", \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Connected", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "车辆温度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "tesla_vehicle_outside_temp_celsius{vin=\"$vin\"}",
     "groupBy": [
      { "params": [ "Connected" ], "type": "tag" }
     ],
     "legendFormat": "outside",
     "measurement": "AllData",
     "query": "SELECT LAST(EA) FROM (SELECT max(\"charge_energy_added\") AS EA FROM \"AllData\" WHERE (\"Connected\" = 'true') AND $timeFilter GROUP BY \"Connected\", \"ConnectedOdometer\")",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Connected", "operator": "=", "value": "true" }
     ]
    },
    {
     "expr": "tesla_vehicle_inside_temp_celsius{vin=\"$vin\"}",
     "legendFormat": "inside"
    }
   ]
  },
  {
   "title": "行驶总里程（单位km）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "lengthkm" }
   ],
   "targets": [
    {
     "expr": "tesla_vehicle_odometer_miles_total{vin=\"$vin\"} * 1.61",
     "legendFormat": "${tesla_name}-总里程"
    }
   ]
  }
 ]
}